MATRICULA_SUFFIX = bytes([1,8,7,1])

TEMPERATURA_INTERNA = b'\x01\x23\xc1' + MATRICULA_SUFFIX + b''

TEMPERATURA_REFERENCIA = b'\x01\x23\xc2' + MATRICULA_SUFFIX + b''

COMANDO_DO_USUARIO = b'\x01\x23\xc3' + MATRICULA_SUFFIX + b''

CONTROLE_DE_SINAL = b'\x01\x23\xd1' + MATRICULA_SUFFIX

LIGAR_DESLIGAR_SISTEMA =  b'\x01\x23\xd3' + MATRICULA_SUFFIX

MODO_DE_CONTROLE =  b'\x01\x23\xd4' + MATRICULA_SUFFIX

SITUACAO_SISTEMA = b'\x01\x23\xd5' + MATRICULA_SUFFIX

LIGAR_FORNO = 161

DESLIGAR_FORNO = 162

LIGAR_SISTEMA = 163

DESLIGAR_SISTEMA = 164

MODO_DEBUG = 165

